# Generated by Django 2.2.2 on 2020-06-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpapitest', '0012_userinfo_usertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeriodicTask',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
